### ISSUE TITLE
trigger animation

### ISSUE THREAD

**Issue by centrespot** [jeremyckahn/mantra#11]
Hi
This is a great tool for creating animations but I am struggling to work out a way of triggering the animation to begin only when the area is visited, for example within the footer area.

**Comment by centrespot** [comment]
Just worked it out...

<script>
document.addEventListener("DOMContentLoaded", function(){
 document.getElementById("mantra").style.animationPlayState = "paused";
});


function PlayAnimation() {
document.getElementById("mantra").style.animationPlayState = "running";
};
</script>

**Comment by jeremyckahn** [comment]
Hi @centrespot, thanks for opening this issue! I'm glad you're enjoying Mantra. This tool doesn't provide functionality around wiring up animations to specific interactions, but you could certainly use it with a library like [Waypoints])(https://github.com/imakewebthings/waypoints) to add a class to an element that would start an animation.

You could also go with a library-less approach like the one you described above. Hopefully this explanation helps you!
