### ISSUE TITLE
Disable text selection for UI elements

### ISSUE THREAD

**Issue by alextegelid** [jeremyckahn/mantra#2]
For fancy feeling. Demo: https://cl.ly/3w3I17372i3w

**Comment by jeremyckahn** [comment]
Good idea!  I will try to get to this when I have a chance to address #3.

FYI, the entire timeline control is actually a separate project called [rekapi-timeline](https://github.com/jeremyckahn/rekapi-timeline), which is embedded into Mantra.  If you'd like to file additional issues related to this part of Mantra's UI (and please do!), please do so in that project!

**Comment by jeremyckahn** [comment]
This has been deployed.  Thanks for reporting!
