### ISSUE TITLE
Opacity seems broken

### ISSUE THREAD

**Issue by MightyFo0l** [jeremyckahn/mantra#26]
Using Opacity values 0 and 100 doesn't seem to transition.

GIF:
![animation tool error](https://user-images.githubusercontent.com/16845714/158782979-eae66666-c1cc-453f-a4da-8becefcc168b.gif)

**Comment by jeremyckahn** [comment]
Hi @MightyFo0l, thanks for opening this issue and the for the helpful GIF! I think that Mantra is working correctly here. To get the effect you want, it looks like you just need to change the opacity value from `100` to `1`. The number in the field represents a [CSS `opacity`](https://developer.mozilla.org/en-US/docs/Web/CSS/opacity#values) value which a normalized number value (from `0` to `1`).

Please give this a try and let me know if works for you!

**Comment by MightyFo0l** [comment]
Ah, that explains it! I was thinking in percentages
