### ISSUE TITLE
Grunt build fails at requirejs:dist?

### ISSUE THREAD

**Issue by zikaari** [jeremyckahn/mantra#4]
Followed the instructions very carefully. Encountered at both develop and master branch.

```
Running "requirejs:dist" (requirejs) task
>> Error: Error: ENOENT: no such file or directory, open 'C:\Users\rootkit_\Desktop\mantra-develop\app\rekapi-timeline.component.container.js'
>> In module tree:
>>     scripts/main
>>       mantra/mantra
>>         mantra/components/container/main
>>           mantra/components/container/view
>>             rekapi-timeline/rekapi-timeline
>>
>>     at Error (native)
Warning: Task "requirejs:dist" failed. Used --force, continuing.
```

**Comment by jeremyckahn** [comment]
Hi @NeekSandhu, thanks for reporting this!  Looks like I forgot to bump the `rekapi-timeline` version — whoops!  Sorry about that.  I've got it `bower link`-ed up on my local machine, so I didn't see this before.  This should be fixed in the `develop` branch, so please pull it down and let me know if it works for you.

**Comment by zikaari** [comment]
Great! Works perfectly fine. However you might wanna have a look at bower file and update the component versions as running `bower install` prompted me asking which version should it install for like 2 or 3 components. I just answered `2` for all and everything works fine so far.

**Comment by jeremyckahn** [comment]
> However you might wanna have a look at bower file and update the component versions as running bower install prompted me asking which version should it install for like 2 or 3 components.

Aye, this issue seems to always come back.  It's a quirk of Bower (this project is built on some fairly old tech). Thanks for the heads up, I just pushed a fix for that to `develop`.
